create extension if not exists pgcrypto;

create table if not exists public.rooms (
  id text primary key check (id = lower(btrim(id)) and id ~ '^[a-z0-9][a-z0-9_-]{2,31}$'),
  owner_id uuid not null references auth.users(id) on delete cascade,
  host_id uuid references auth.users(id) on delete set null,
  words_id text not null references word_bank.lists(id),
  max_rounds integer not null default 8 check (max_rounds between 1 and 20),
  max_time integer not null default 120 check (max_time between 10 and 600),
  tries_per_user integer not null default 0 check (tries_per_user between 0 and 50),
  status text not null default 'waiting' check (status in ('waiting', 'playing', 'finished')),
  round_number integer not null default 0 check (round_number >= 0),
  round_ends_at timestamptz,
  expires_at timestamptz not null default (now() + interval '10 minutes'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.room_members (
  room_id text not null references public.rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null check (nickname = btrim(nickname) and length(nickname) between 1 and 20),
  score integer not null default 0 check (score >= 0),
  guessed boolean not null default false,
  tries_left integer not null default 0 check (tries_left >= 0),
  joined_at timestamptz not null default now(),
  last_heartbeat timestamptz not null default now(),
  primary key (room_id, user_id),
  unique (room_id, nickname)
);

create unique index if not exists room_members_nickname_ci_idx
  on public.room_members (room_id, lower(nickname));

create table if not exists public.room_rounds (
  id uuid primary key default gen_random_uuid(),
  room_id text not null references public.rooms(id) on delete cascade,
  round_number integer not null check (round_number > 0),
  drawer_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique (room_id, round_number)
);

create table if not exists game_private.round_secrets (
  round_id uuid primary key references public.room_rounds(id) on delete cascade,
  room_id text not null references public.rooms(id) on delete cascade,
  word_id bigint not null references word_bank.entries(id),
  created_at timestamptz not null default now()
);

create table if not exists public.room_messages (
  id bigint generated by default as identity primary key,
  room_id text not null references public.rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  text text not null check (length(btrim(text)) between 1 and 500),
  color text not null default '#ffffff' check (color ~ '^#[0-9a-fA-F]{6}$'),
  created_at timestamptz not null default now()
);

create table if not exists public.drawing_strokes (
  id bigint generated by default as identity primary key,
  room_id text not null references public.rooms(id) on delete cascade,
  round_id uuid not null references public.room_rounds(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  line jsonb not null,
  opts jsonb not null,
  created_at timestamptz not null default now(),
  check (jsonb_typeof(line) = 'array' and jsonb_array_length(line) = 2),
  check (jsonb_typeof(opts) = 'object')
);

create index if not exists room_members_room_idx on public.room_members(room_id, joined_at);
create index if not exists room_rounds_room_idx on public.room_rounds(room_id, round_number desc);
create index if not exists room_messages_room_idx on public.room_messages(room_id, created_at desc);
create index if not exists drawing_strokes_round_idx on public.drawing_strokes(room_id, round_id, id);
create index if not exists rooms_expiration_idx on public.rooms(expires_at) where status <> 'playing';

alter table public.rooms enable row level security;
alter table public.room_members enable row level security;
alter table public.room_rounds enable row level security;
alter table public.room_messages enable row level security;
alter table public.drawing_strokes enable row level security;
alter table game_private.round_secrets enable row level security;

revoke all on public.rooms, public.room_members, public.room_rounds, public.room_messages, public.drawing_strokes from anon;
revoke insert, update, delete on public.rooms, public.room_members, public.room_rounds, public.room_messages, public.drawing_strokes from authenticated;
grant usage on schema public to authenticated;
grant select on public.rooms, public.room_members, public.room_rounds, public.room_messages, public.drawing_strokes to authenticated;
revoke all on schema game_private from public, anon, authenticated;
revoke all on all tables in schema game_private from public, anon, authenticated;

create or replace function game_private.is_room_member(
  requested_room_id text,
  requested_user_id uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = public, game_private, auth
as $$
  select requested_user_id is not null and exists (
    select 1 from public.room_members member
    where member.room_id = lower(btrim(requested_room_id))
      and member.user_id = requested_user_id
  )
$$;

revoke all on function game_private.is_room_member(text, uuid) from public, anon, authenticated;
grant usage on schema game_private to authenticated;
grant execute on function game_private.is_room_member(text, uuid) to authenticated;

create policy "room members can read their room"
  on public.rooms for select to authenticated
  using (game_private.is_room_member(id));

create policy "room members can read member state"
  on public.room_members for select to authenticated
  using (game_private.is_room_member(room_id));

create policy "room members can read round metadata"
  on public.room_rounds for select to authenticated
  using (game_private.is_room_member(room_id));

create policy "room members can read chat"
  on public.room_messages for select to authenticated
  using (game_private.is_room_member(room_id));

create policy "room members can read drawing history"
  on public.drawing_strokes for select to authenticated
  using (game_private.is_room_member(room_id));

create or replace function game_private.safe_snapshot(requested_room_id text, include_history boolean default true)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, game_private, auth
as $$
declare
  room_row public.rooms%rowtype;
  current_round public.room_rounds%rowtype;
  room_json jsonb;
  members_json jsonb;
  messages_json jsonb;
  strokes_json jsonb;
begin
  select * into room_row from public.rooms where id = lower(btrim(requested_room_id));
  if room_row.id is null then
    raise exception using errcode = 'P0002', message = 'The room does not exist.';
  end if;

  select * into current_round
  from public.room_rounds
  where room_id = room_row.id and round_number = room_row.round_number;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', member.user_id,
    '_id', member.user_id,
    'name', member.nickname,
    'nickname', member.nickname,
    'points', member.score,
    'score', member.score,
    'guessed', member.guessed,
    'tries_left', member.tries_left,
    'triesLeft', member.tries_left,
    'last_heartbeat', member.last_heartbeat
  ) order by member.joined_at), '[]'::jsonb)
  into members_json
  from public.room_members member where member.room_id = room_row.id;

  room_json := jsonb_build_object(
    'id', room_row.id,
    '_id', room_row.id,
    'owner_id', room_row.owner_id,
    'host_id', room_row.host_id,
    'owner', (select jsonb_build_object('id', m.user_id, '_id', m.user_id, 'name', m.nickname) from public.room_members m where m.room_id = room_row.id and m.user_id = room_row.owner_id),
    'host', (select jsonb_build_object('id', m.user_id, '_id', m.user_id, 'name', m.nickname) from public.room_members m where m.room_id = room_row.id and m.user_id = room_row.host_id),
    'words_id', room_row.words_id,
    'max_rounds', room_row.max_rounds,
    'max_time', room_row.max_time,
    'tries_per_user', room_row.tries_per_user,
    'status', room_row.status,
    'is_start', room_row.status = 'playing',
    'round_number', room_row.round_number,
    'round', room_row.round_number,
    'round_id', current_round.id,
    'round_ends_at', room_row.round_ends_at,
    'time', case when room_row.status = 'playing' and room_row.round_ends_at is not null then greatest(0, ceil(extract(epoch from (room_row.round_ends_at - now())))::integer) else 0 end,
    'expires_at', room_row.expires_at
  );

  if include_history then
    select coalesce(jsonb_agg(jsonb_build_object(
      'id', message.id,
      'user', jsonb_build_object('id', message.user_id, '_id', message.user_id, 'name', member.nickname),
      'text', message.text,
      'color', message.color,
      'created_at', message.created_at
    ) order by message.created_at), '[]'::jsonb)
    into messages_json
    from (select * from public.room_messages where room_id = room_row.id order by created_at desc limit 100) message
    join public.room_members member on member.room_id = message.room_id and member.user_id = message.user_id;

    select coalesce(jsonb_agg(jsonb_build_object(
      'id', stroke.id,
      'line', stroke.line,
      'opts', stroke.opts
    ) order by stroke.id), '[]'::jsonb)
    into strokes_json
    from public.drawing_strokes stroke
    where stroke.room_id = room_row.id and stroke.round_id = current_round.id;
  else
    messages_json := '[]'::jsonb;
    strokes_json := '[]'::jsonb;
  end if;

  return jsonb_build_object(
    'room', room_json,
    'users', members_json,
    'messages', messages_json,
    'strokes', strokes_json,
    'self_id', auth.uid()
  );
end
$$;

create or replace function game_private.broadcast_room_event(requested_room_id text, event_name text, event_payload jsonb)
returns void
language plpgsql
security definer
set search_path = public, game_private, realtime
as $$
begin
  perform realtime.send(event_payload, event_name, 'room:' || requested_room_id, true);
end
$$;

revoke all on function game_private.safe_snapshot(text, boolean) from public, anon, authenticated;
revoke all on function game_private.broadcast_room_event(text, text, jsonb) from public, anon, authenticated;

-- Realtime authorization is intentionally scoped to room members and a user's own topic.
drop policy if exists "authenticated room members can receive room broadcasts" on realtime.messages;
drop policy if exists "authenticated room members can send room broadcasts" on realtime.messages;
create policy "authenticated room members can receive room broadcasts"
  on realtime.messages for select to authenticated
  using (
    (topic like 'room:%' and game_private.is_room_member(substring(topic from 6)))
    or topic = 'user:' || (select auth.uid())::text
  );
