create schema if not exists word_bank;
create schema if not exists game_private;

create table if not exists word_bank.lists (
  id text primary key check (id ~ '^[a-z0-9_-]{2,32}$'),
  display_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists word_bank.entries (
  id bigint generated by default as identity primary key,
  list_id text not null references word_bank.lists(id) on delete cascade,
  slug text not null,
  word text not null check (length(btrim(word)) between 1 and 120),
  metadata jsonb not null default '{}'::jsonb,
  unique (list_id, slug)
);

create index if not exists word_bank_entries_list_id_idx on word_bank.entries(list_id);

alter table word_bank.lists enable row level security;
alter table word_bank.entries enable row level security;

revoke all on schema word_bank from public, anon, authenticated;
revoke all on all tables in schema word_bank from public, anon, authenticated;
revoke all on all sequences in schema word_bank from public, anon, authenticated;

create or replace function game_private.normalize_word(value text)
returns text
language sql
immutable
parallel safe
as $$
  select lower(regexp_replace(btrim(coalesce(value, '')), '''', '', 'g'))
$$;

revoke all on function game_private.normalize_word(text) from public, anon, authenticated;
